// <auto-generated />
using System;
using DotNetComputerSekho.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNetComputerSekho.Migrations
{
    [DbContext(typeof(AppDBcontext))]
    [Migration("20230831072659_remove_FK")]
    partial class remove_FK
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotNetComputerSekho.Entities.Enquiry", b =>
                {
                    b.Property<int>("enquiry_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("enquiry_id"));

                    b.Property<DateTime>("Follow_up_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("closure_reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("enquirer_email_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("enquirer_mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("enquirer_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("enquirer_query")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("enquiry_date")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("enquiry_processed_flag")
                        .HasColumnType("bit");

                    b.Property<string>("followup_msg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("staff_id")
                        .HasColumnType("int");

                    b.HasKey("enquiry_id");

                    b.ToTable("Enquiry");
                });

            modelBuilder.Entity("DotNetComputerSekho.Entities.Followup", b =>
                {
                    b.Property<int>("followup_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("followup_id"));

                    b.Property<int>("enquiry_id")
                        .HasColumnType("int");

                    b.Property<string>("followup_msg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("staff_id")
                        .HasColumnType("int");

                    b.HasKey("followup_id");

                    b.ToTable("Followup");
                });

            modelBuilder.Entity("DotNetComputerSekho.Entities.Placement", b =>
                {
                    b.Property<int>("placemetid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("placemetid"));

                    b.Property<int>("batchid")
                        .HasColumnType("int");

                    b.Property<string>("coursename")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("placedstudents")
                        .HasColumnType("int");

                    b.Property<int>("total_student")
                        .HasColumnType("int");

                    b.HasKey("placemetid");

                    b.ToTable("Placement");
                });

            modelBuilder.Entity("DotNetComputerSekho.Entities.Staff", b =>
                {
                    b.Property<int>("staff_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("staff_id"));

                    b.Property<string>("photo_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("staff_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("staff_isactive")
                        .HasColumnType("bit");

                    b.Property<string>("staff_mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("staff_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("staff_password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("staff_role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("staff_username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("staff_id");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("DotNetComputerSekho.Models.Batch", b =>
                {
                    b.Property<int>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("batch_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BatchId"));

                    b.Property<DateTime>("BatchEndTime")
                        .HasColumnType("date")
                        .HasColumnName("batch_end_time");

                    b.Property<decimal?>("BatchFees")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("batch_fees");

                    b.Property<string>("BatchName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("batch_name");

                    b.Property<DateTime>("BatchStartTime")
                        .HasColumnType("date")
                        .HasColumnName("batch_start_time");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FinalPresentationDate")
                        .HasColumnType("date")
                        .HasColumnName("final_presentation_date");

                    b.HasKey("BatchId");

                    b.HasIndex("CourseId");

                    b.ToTable("Batch");
                });

            modelBuilder.Entity("DotNetComputerSekho.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("AgeGroupType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("age_grp_type");

                    b.Property<string>("CourseDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("course_description");

                    b.Property<int>("CourseDuration")
                        .HasColumnType("int")
                        .HasColumnName("course_duration");

                    b.Property<bool>("CourseIsActive")
                        .HasColumnType("bit")
                        .HasColumnName("course_is_active");

                    b.Property<string>("CourseName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("course_name");

                    b.Property<string>("CourseSyllabus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("course_syllabus");

                    b.Property<string>("CoverPhoto")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cover_photo");

                    b.Property<int>("VideoId")
                        .HasColumnType("int")
                        .HasColumnName("video_id");

                    b.HasKey("CourseId");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("DotNetComputerSekho.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<int>("BatchId")
                        .HasColumnType("int")
                        .HasColumnName("batch_id");

                    b.Property<string>("StudentAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("student_address");

                    b.Property<DateTime>("StudentDob")
                        .HasColumnType("date")
                        .HasColumnName("student_dob");

                    b.Property<string>("StudentGender")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("student_gender");

                    b.Property<string>("StudentMobile")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("student_mobile");

                    b.Property<string>("StudentName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("student_name");

                    b.Property<string>("StudentQualification")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("student_qualification");

                    b.HasKey("StudentId");

                    b.HasIndex("BatchId");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("DotNetComputerSekho.Models.Batch", b =>
                {
                    b.HasOne("DotNetComputerSekho.Models.Course", "Course")
                        .WithMany("Batches")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("DotNetComputerSekho.Models.Student", b =>
                {
                    b.HasOne("DotNetComputerSekho.Models.Batch", "Batch")
                        .WithMany("Students")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("DotNetComputerSekho.Models.Batch", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("DotNetComputerSekho.Models.Course", b =>
                {
                    b.Navigation("Batches");
                });
#pragma warning restore 612, 618
        }
    }
}
