// <auto-generated />
using System;
using DotNetComputerSekho.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNetComputerSekho.Migrations
{
    [DbContext(typeof(AppDBcontext))]
    [Migration("20230831051202_put")]
    partial class put
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotNetComputerSekho.Entities.Enquiry", b =>
                {
                    b.Property<int>("enquiry_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("enquiry_id"));

                    b.Property<DateTime>("Follow_up_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("closure_reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("enquirer_email_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("enquirer_mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("enquirer_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("enquirer_query")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("enquiry_date")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("enquiry_processed_flag")
                        .HasColumnType("bit");

                    b.Property<string>("followup_msg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("staff_id")
                        .HasColumnType("int");

                    b.HasKey("enquiry_id");

                    b.ToTable("Enquiry");
                });

            modelBuilder.Entity("DotNetComputerSekho.Entities.Followup", b =>
                {
                    b.Property<int>("followup_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("followup_id"));

                    b.Property<int>("enquiry_id")
                        .HasColumnType("int");

                    b.Property<string>("followup_msg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("staff_id")
                        .HasColumnType("int");

                    b.HasKey("followup_id");

                    b.ToTable("Followup");
                });

            modelBuilder.Entity("DotNetComputerSekho.Entities.Placement", b =>
                {
                    b.Property<int>("placemetid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("placemetid"));

                    b.Property<int>("batchid")
                        .HasColumnType("int");

                    b.Property<string>("coursename")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("placedstudents")
                        .HasColumnType("int");

                    b.Property<int>("total_student")
                        .HasColumnType("int");

                    b.HasKey("placemetid");

                    b.ToTable("Placements");
                });

            modelBuilder.Entity("DotNetComputerSekho.Entities.Staff", b =>
                {
                    b.Property<int>("staff_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("staff_id"));

                    b.Property<string>("photo_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("staff_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("staff_isactive")
                        .HasColumnType("bit");

                    b.Property<string>("staff_mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("staff_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("staff_password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("staff_role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("staff_username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("staff_id");

                    b.ToTable("Staff");
                });
#pragma warning restore 612, 618
        }
    }
}
